// SPDX-License-Identifier: AGPL-3.0-only
//! Applying a bundle **into** a deployment.
//!
//! Upsert only. Nothing is ever deleted and there is deliberately no "replace" mode — it would be
//! one boolean away, and that boolean is what makes an import unrecoverable. `dry_run` is this same
//! code path with a rollback at the end rather than a second, less-tested one.
//!
//! The tables are walked in [`super::BUNDLE_TABLES`] order, which is dependency order: a block
//! keeps the id set it wrote, and a later block drops a reference the target cannot resolve rather
//! than failing the row.

use super::*;
use crate::cadence::{compute_next_run, Cadence, Schedule};
use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};
use sqlx::{Postgres, Row, Transaction};
use std::collections::{BTreeMap, HashSet};
use uuid::Uuid;

impl ConfigBundleRepo {
    /// Apply a bundle. Upsert only — nothing is ever deleted. With `dry_run` the whole import runs
    /// and is then rolled back, so the report describes exactly what a real run would do.
    ///
    /// The two halves below are not a style choice. [`import_inventory::write`] writes what
    /// everything else points *at* and hands back the ids it wrote; [`import_attached::write`]
    /// takes those ids and writes what points *back*. The second cannot run before the first
    /// because it needs the value the first returns — an ordering that used to be held up by
    /// nothing but the order of statements inside one 706-line function.
    ///
    /// The transaction is passed **by value and handed back**, unlike the two accumulators, and the
    /// asymmetry is deliberate: it is *consumed and handed on*, while `notes` and `counts` are
    /// written into. It also keeps every `&mut tx` and `&mut *tx` in the two bodies as the code that
    /// was already there — `&mut Transaction` would have rewritten each of them, in a file no unit
    /// test can reach. An early `?` drops it, which rolls back, exactly as an early return did
    /// before the split.
    pub async fn import(
        &self,
        bundle: &ConfigBundle,
        dry_run: bool,
    ) -> Result<ImportReport, BundleError> {
        check_header(bundle)?;
        let now = Utc::now();
        let mut notes = Notes::default();
        let mut counts: BTreeMap<&'static str, TableResult> = BTreeMap::new();
        let tx = self.pool.begin().await?;

        let (tx, ids) = import_inventory::write(tx, bundle, &mut notes, &mut counts).await?;
        let tx = import_attached::write(tx, bundle, now, &mut notes, &mut counts, ids).await?;

        if dry_run {
            tx.rollback().await?;
        } else {
            tx.commit().await?;
        }

        Ok(ImportReport {
            dry_run,
            tables: BUNDLE_TABLES
                .iter()
                .filter_map(|t| counts.remove(*t))
                .collect(),
            notes: notes.finish(),
        })
    }
}

/// What the inventory half wrote, and the credentials the target already holds.
///
/// Exactly these four cross the boundary between the two halves — measured, not assumed. Three
/// more id sets exist (`template_ids`, `source_ids`, `definition_ids`) and every one of them is
/// consumed in the block below the one that makes it, so none of them is here.
///
/// No `Default`: a field added to this struct turns every construction into a compile error
/// rather than a silently empty set, which is the difference between a dropped reference being
/// reported and being invisible.
pub(super) struct Ids {
    pub(super) profiles: HashSet<Uuid>,
    pub(super) groups: HashSet<Uuid>,
    pub(super) nodes: HashSet<Uuid>,
    /// Read, never written: the importer carries only credential *ids*, and keeps one when the
    /// target already holds that exact id.
    pub(super) credentials: HashSet<Uuid>,
}

/// Keep a reference only if the target has its target; otherwise clear it and count a note.
pub(super) fn keep_ref(
    id: Option<Uuid>,
    known: &HashSet<Uuid>,
    notes: &mut Notes,
    table: &str,
    field: &str,
) -> Option<Uuid> {
    match id {
        Some(v) if known.contains(&v) => Some(v),
        Some(_) => {
            notes.add(table, NoteCode::ReferenceDropped, Some(field));
            None
        }
        None => None,
    }
}

/// The next firing instant for a preset cadence, recomputed on the target's clock.
pub(super) fn next_run(
    frequency: &str,
    day_of_week: Option<i16>,
    day_of_month: Option<i16>,
    at_hour: i16,
    at_minute: i16,
    now: DateTime<Utc>,
) -> DateTime<Utc> {
    compute_next_run(
        Schedule {
            frequency: Cadence::from_stored(frequency),
            day_of_week,
            day_of_month,
            at_hour,
            at_minute,
        },
        now,
    )
}

/// A SHA-256 digest of 32 freshly generated bytes that are never returned or stored.
///
/// Used only where a column requires a token digest and no token may cross deployments. The result
/// is a well-formed digest whose preimage nobody holds, so it authenticates nothing.
pub(super) fn unusable_token_hash() -> String {
    let bytes: [u8; 32] = rand::random();
    let digest = Sha256::digest(bytes);
    let mut s = String::with_capacity(64);
    for b in digest {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// The set of ids a table already holds, read inside the import transaction so it sees this
/// import's own inserts. The SQL is a `&'static str` literal at every call site — nothing here is
/// built from a request.
pub(super) async fn id_set(
    tx: &mut Transaction<'_, Postgres>,
    sql: &'static str,
) -> Result<HashSet<Uuid>, sqlx::Error> {
    let rows = sqlx::query(sql).fetch_all(&mut **tx).await?;
    rows.into_iter()
        .map(|r| r.try_get::<Uuid, _>("id"))
        .collect()
}

pub(super) fn counter<'a>(
    counts: &'a mut BTreeMap<&'static str, TableResult>,
    table: &'static str,
) -> &'a mut TableResult {
    counts.entry(table).or_insert_with(|| TableResult {
        table: table.to_owned(),
        created: 0,
        updated: 0,
        skipped: 0,
    })
}

/// Count a written row as created or updated, and remember its id for later references.
pub(super) fn bump(c: &mut TableResult, seen: &mut HashSet<Uuid>, id: Uuid) {
    if seen.insert(id) {
        c.created += 1;
    } else {
        c.updated += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A dangling reference is cleared and counted; a resolvable one is kept untouched.
    #[test]
    fn a_dangling_reference_is_dropped_and_reported() {
        let known: HashSet<Uuid> = [Uuid::from_u128(7)].into_iter().collect();
        let mut notes = Notes::default();
        assert_eq!(
            keep_ref(
                Some(Uuid::from_u128(7)),
                &known,
                &mut notes,
                "nodes",
                "profile_id"
            ),
            Some(Uuid::from_u128(7))
        );
        assert_eq!(
            keep_ref(
                Some(Uuid::from_u128(8)),
                &known,
                &mut notes,
                "nodes",
                "profile_id"
            ),
            None
        );
        assert_eq!(
            keep_ref(None, &known, &mut notes, "nodes", "profile_id"),
            None
        );
        let out = notes.finish();
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].code, NoteCode::ReferenceDropped);
        assert_eq!(out[0].field.as_deref(), Some("profile_id"));
        assert_eq!(out[0].count, 1);
    }

    /// The unusable webhook digest must be digest-shaped and never repeat, so it cannot be guessed
    /// from another import.
    #[test]
    fn the_placeholder_webhook_digest_is_shaped_like_one_and_never_repeats() {
        let a = unusable_token_hash();
        let b = unusable_token_hash();
        assert_eq!(a.len(), 64);
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
        assert_ne!(a, b);
    }

    /// A recomputed schedule always fires in the future — never at an instant already past, which
    /// is what carrying the source deployment's `next_run_at` would have produced.
    #[test]
    fn a_recomputed_schedule_fires_in_the_future() {
        let now = DateTime::parse_from_rfc3339("2026-03-05T12:34:00Z")
            .unwrap()
            .with_timezone(&Utc);
        for (freq, dow, dom) in [
            ("daily", None, None),
            ("weekly", Some(3), None),
            ("monthly", None, Some(28)),
            // An unknown cadence from a newer core still yields a usable instant.
            ("hourly-ish", None, None),
        ] {
            let next = next_run(freq, dow, dom, 2, 15, now);
            assert!(next > now, "{freq} produced a past instant: {next}");
        }
    }
}
