// SPDX-License-Identifier: AGPL-3.0-only
//! Applying a bundle **into** a deployment.
//!
//! Upsert only. Nothing is ever deleted and there is deliberately no "replace" mode — it would be
//! one boolean away, and that boolean is what makes an import unrecoverable. `dry_run` is this same
//! code path with a rollback at the end rather than a second, less-tested one.
//!
//! The tables are walked in [`super::BUNDLE_TABLES`] order, which is dependency order: a block
//! keeps the id set it wrote, and a later block drops a reference the target cannot resolve rather
//! than failing the row.

use super::*;
use crate::cadence::{compute_next_run, Cadence, Schedule};
use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};
use sqlx::{Postgres, Row, Transaction};
use std::collections::{BTreeMap, HashSet};
use uuid::Uuid;

impl ConfigBundleRepo {
    /// Apply a bundle. Upsert only — nothing is ever deleted. With `dry_run` the whole import runs
    /// and is then rolled back, so the report describes exactly what a real run would do.
    ///
    /// The two halves below are not a style choice. [`import_inventory::write`] writes what
    /// everything else points *at* and hands back the ids it wrote; [`import_attached::write`]
    /// takes those ids and writes what points *back*. The second cannot run before the first
    /// because it needs the value the first returns — an ordering that used to be held up by
    /// nothing but the order of statements inside one 706-line function.
    ///
    /// The transaction is passed **by value and handed back**, unlike the two accumulators, and the
    /// asymmetry is deliberate: it is *consumed and handed on*, while `notes` and `counts` are
    /// written into. It also keeps every `&mut tx` and `&mut *tx` in the two bodies as the code that
    /// was already there — `&mut Transaction` would have rewritten each of them, in a file no unit
    /// test can reach. An early `?` drops it, which rolls back, exactly as an early return did
    /// before the split.
    pub async fn import(
        &self,
        bundle: &ConfigBundle,
        dry_run: bool,
    ) -> Result<ImportReport, BundleError> {
        check_header(bundle)?;
        let now = Utc::now();
        let mut notes = Notes::default();
        let mut counts: BTreeMap<&'static str, TableResult> = BTreeMap::new();
        let tx = self.pool.begin().await?;

        let (tx, ids) = import_inventory::write(tx, bundle, &mut notes, &mut counts).await?;
        let tx = import_attached::write(tx, bundle, now, &mut notes, &mut counts, ids).await?;

        if dry_run {
            tx.rollback().await?;
        } else {
            tx.commit().await?;
        }

        Ok(ImportReport {
            dry_run,
            tables: BUNDLE_TABLES
                .iter()
                .filter_map(|t| counts.remove(*t))
                .collect(),
            notes: notes.finish(),
        })
    }
}

/// What the inventory half wrote, and the credentials the target already holds.
///
/// Exactly these four cross the boundary between the two halves — measured, not assumed. Three
/// more id sets exist (`template_ids`, `source_ids`, `definition_ids`) and every one of them is
/// consumed in the block below the one that makes it, so none of them is here.
///
/// No `Default`: a field added to this struct turns every construction into a compile error
/// rather than a silently empty set, which is the difference between a dropped reference being
/// reported and being invisible.
pub(super) struct Ids {
    pub(super) profiles: HashSet<Uuid>,
    pub(super) groups: HashSet<Uuid>,
    pub(super) nodes: HashSet<Uuid>,
    /// Read, never written: the importer carries only credential *ids*, and keeps one when the
    /// target already holds that exact id.
    pub(super) credentials: HashSet<Uuid>,
}

/// Keep a reference only if the target has its target; otherwise clear it and count a note.
pub(super) fn keep_ref(
    id: Option<Uuid>,
    known: &HashSet<Uuid>,
    notes: &mut Notes,
    table: &str,
    field: &str,
) -> Option<Uuid> {
    match id {
        Some(v) if known.contains(&v) => Some(v),
        Some(_) => {
            notes.add(table, NoteCode::ReferenceDropped, Some(field));
            None
        }
        None => None,
    }
}

/// The next firing instant for a preset cadence, recomputed on the target's clock.
pub(super) fn next_run(
    frequency: &str,
    day_of_week: Option<i16>,
    day_of_month: Option<i16>,
    at_hour: i16,
    at_minute: i16,
    now: DateTime<Utc>,
) -> DateTime<Utc> {
    compute_next_run(
        Schedule {
            frequency: Cadence::from_stored(frequency),
            day_of_week,
            day_of_month,
            at_hour,
            at_minute,
        },
        now,
    )
}

/// A SHA-256 digest of 32 freshly generated bytes that are never returned or stored.
///
/// Used only where a column requires a token digest and no token may cross deployments. The result
/// is a well-formed digest whose preimage nobody holds, so it authenticates nothing.
pub(super) fn unusable_token_hash() -> String {
    let bytes: [u8; 32] = rand::random();
    let digest = Sha256::digest(bytes);
    let mut s = String::with_capacity(64);
    for b in digest {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// The set of ids a table already holds, read inside the import transaction so it sees this
/// import's own inserts. The SQL is a `&'static str` literal at every call site — nothing here is
/// built from a request.
pub(super) async fn id_set(
    tx: &mut Transaction<'_, Postgres>,
    sql: &'static str,
) -> Result<HashSet<Uuid>, sqlx::Error> {
    let rows = sqlx::query(sql).fetch_all(&mut **tx).await?;
    rows.into_iter()
        .map(|r| r.try_get::<Uuid, _>("id"))
        .collect()
}

pub(super) fn counter<'a>(
    counts: &'a mut BTreeMap<&'static str, TableResult>,
    table: &'static str,
) -> &'a mut TableResult {
    counts.entry(table).or_insert_with(|| TableResult {
        table: table.to_owned(),
        created: 0,
        updated: 0,
        skipped: 0,
    })
}

/// Count a written row as created or updated, and remember its id for later references.
pub(super) fn bump(c: &mut TableResult, seen: &mut HashSet<Uuid>, id: Uuid) {
    if seen.insert(id) {
        c.created += 1;
    } else {
        c.updated += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A dangling reference is cleared and counted; a resolvable one is kept untouched.
    #[test]
    fn a_dangling_reference_is_dropped_and_reported() {
        let known: HashSet<Uuid> = [Uuid::from_u128(7)].into_iter().collect();
        let mut notes = Notes::default();
        assert_eq!(
            keep_ref(
                Some(Uuid::from_u128(7)),
                &known,
                &mut notes,
                "nodes",
                "profile_id"
            ),
            Some(Uuid::from_u128(7))
        );
        assert_eq!(
            keep_ref(
                Some(Uuid::from_u128(8)),
                &known,
                &mut notes,
                "nodes",
                "profile_id"
            ),
            None
        );
        assert_eq!(
            keep_ref(None, &known, &mut notes, "nodes", "profile_id"),
            None
        );
        let out = notes.finish();
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].code, NoteCode::ReferenceDropped);
        assert_eq!(out[0].field.as_deref(), Some("profile_id"));
        assert_eq!(out[0].count, 1);
    }

    /// The unusable webhook digest must be digest-shaped and never repeat, so it cannot be guessed
    /// from another import.
    #[test]
    fn the_placeholder_webhook_digest_is_shaped_like_one_and_never_repeats() {
        let a = unusable_token_hash();
        let b = unusable_token_hash();
        assert_eq!(a.len(), 64);
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
        assert_ne!(a, b);
    }

    /// A recomputed schedule always fires in the future — never at an instant already past, which
    /// is what carrying the source deployment's `next_run_at` would have produced.
    #[test]
    fn a_recomputed_schedule_fires_in_the_future() {
        let now = DateTime::parse_from_rfc3339("2026-03-05T12:34:00Z")
            .unwrap()
            .with_timezone(&Utc);
        for (freq, dow, dom) in [
            ("daily", None, None),
            ("weekly", Some(3), None),
            ("monthly", None, Some(28)),
            // An unknown cadence from a newer core still yields a usable instant.
            ("hourly-ish", None, None),
        ] {
            let next = next_run(freq, dow, dom, 2, 15, now);
            assert!(next > now, "{freq} produced a past instant: {next}");
        }
    }

    /// Which tables the round trip must fill, and the number of rows [`testkit::full_bundle`] puts
    /// in each. Written out rather than derived from the bundle: the point of the fixture is that
    /// every collection is non-empty, and a table that quietly lost its row would still satisfy a
    /// count derived from the same value.
    #[cfg(test)]
    const EXPECTED_ROWS: [(&str, i64); 16] = [
        ("profiles", 2),
        ("collection_templates", 1),
        ("collection_template_items", 1),
        ("profile_collection_templates", 1),
        ("classification_rules", 1),
        ("node_groups", 2),
        ("nodes", 2),
        ("thresholds", 1),
        ("url_checks", 1),
        ("dns_checks", 1),
        ("forward_destinations", 1),
        ("event_sources", 1),
        ("event_rules", 1),
        ("report_definitions", 1),
        ("report_schedules", 1),
        ("analysis_schedules", 1),
    ];

    /// The fifteen tables the module doc says a bundle deliberately does not carry.
    ///
    /// `config_bundle/guards.rs` already refuses a *write* to any of them by reading this module's
    /// text. This is the other half: the import actually runs, and they are still empty afterwards.
    /// A guard that reads text cannot see a write performed through a helper.
    #[cfg(test)]
    const NEVER_CARRIED: [&str; 15] = [
        "users",
        "api_tokens",
        "credentials",
        "notification_channels",
        "routing_rules",
        "ldap_config",
        "oidc_providers",
        "llm_config",
        "meraki_orgs",
        "pollers",
        "mib_catalog",
        "user_dashboards",
        "shared_dashboard",
        "user_preferences",
        "maintenance_windows",
    ];

    /// Every table the bundle carries arrives, and nothing is dropped on the way in.
    ///
    /// This is the test ADR-116 exists for. Before it, `import_inventory.rs` and
    /// `import_attached.rs` ran **two of their ten statements each** under the whole suite: every
    /// statement sits in a `for … in &bundle.<collection>`, and the only round trip that existed
    /// exported a deployment holding one group.
    ///
    /// 🚨 The three `parent_id` assertions are the ones worth keeping. Each of profiles, groups and
    /// nodes applies its parent in a **second pass**, so a bundle whose rows are all roots imports
    /// perfectly while three `UPDATE`s never execute.
    #[sqlx::test(migrator = "crate::repo::MIGRATIONS")]
    #[ignore = "needs DATABASE_URL"]
    async fn a_bundle_that_fills_every_collection_imports_into_an_empty_deployment(
        pool: sqlx::PgPool,
    ) {
        let bundle = testkit::full_bundle();
        let mut before = Vec::new();
        for (table, _) in EXPECTED_ROWS {
            before.push(crate::pgtest::rows(&pool, table).await);
        }

        let report = ConfigBundleRepo::new(pool.clone())
            .import(&bundle, false)
            .await
            .expect("import");
        assert!(!report.dry_run);

        for (i, (table, want)) in EXPECTED_ROWS.into_iter().enumerate() {
            let after = crate::pgtest::rows(&pool, table).await;
            assert_eq!(
                after - before[i],
                want,
                "{table} gained the wrong row count"
            );
        }

        // Nothing was dropped or skipped for want of a reference: the fixture is self-consistent,
        // so any such note means the importer could not resolve something it was handed.
        for note in &report.notes {
            assert!(
                !matches!(
                    note.code,
                    NoteCode::SkippedMissingReference
                        | NoteCode::SkippedInvalidValue
                        | NoteCode::ReferenceDropped
                ),
                "{:?} on {} ({:?})",
                note.code,
                note.table,
                note.field
            );
        }

        // The second pass, for each of the three tables that has one.
        for (table, child, parent) in [
            ("profiles", bundle.profiles[1].id, bundle.profiles[0].id),
            (
                "node_groups",
                bundle.node_groups[1].id,
                bundle.node_groups[0].id,
            ),
            ("nodes", bundle.nodes[1].id, bundle.nodes[0].id),
        ] {
            let got: Option<Uuid> =
                sqlx::query_scalar(&format!("SELECT parent_id FROM {table} WHERE id = $1"))
                    .bind(child)
                    .fetch_one(&pool)
                    .await
                    .unwrap_or_else(|e| panic!("read {table}.parent_id: {e}"));
            assert_eq!(got, Some(parent), "{table} never had its parent applied");
        }
    }

    /// `dry_run` runs the whole import and commits none of it.
    ///
    /// The report is the same one a real run would produce — that is the point of it being the same
    /// code path with a rollback rather than a second, less-tested one — so this asserts the report
    /// is populated *and* the tables are untouched. Asserting only the second would pass for an
    /// importer that did nothing at all.
    #[sqlx::test(migrator = "crate::repo::MIGRATIONS")]
    #[ignore = "needs DATABASE_URL"]
    async fn a_dry_run_reports_what_it_would_do_and_writes_none_of_it(pool: sqlx::PgPool) {
        let bundle = testkit::full_bundle();
        let mut before = Vec::new();
        for (table, _) in EXPECTED_ROWS {
            before.push(crate::pgtest::rows(&pool, table).await);
        }

        let report = ConfigBundleRepo::new(pool.clone())
            .import(&bundle, true)
            .await
            .expect("dry run");
        assert!(report.dry_run);
        assert_eq!(report.tables.len(), EXPECTED_ROWS.len());
        for (table, want) in EXPECTED_ROWS {
            let r = report
                .tables
                .iter()
                .find(|t| t.table == table)
                .unwrap_or_else(|| panic!("{table} missing from the report"));
            assert_eq!(i64::from(r.created), want, "{table} created count");
        }

        for (i, (table, _)) in EXPECTED_ROWS.into_iter().enumerate() {
            assert_eq!(
                crate::pgtest::rows(&pool, table).await,
                before[i],
                "{table} was written by a dry run"
            );
        }
    }

    /// Importing the same bundle twice updates every row and creates none.
    ///
    /// The importer is upsert-only, so the second run is the case an operator actually hits — a
    /// bundle re-applied after an edit. A row counted as created twice would mean a duplicate.
    #[sqlx::test(migrator = "crate::repo::MIGRATIONS")]
    #[ignore = "needs DATABASE_URL"]
    async fn the_same_bundle_imported_twice_creates_nothing_the_second_time(pool: sqlx::PgPool) {
        let bundle = testkit::full_bundle();
        let repo = ConfigBundleRepo::new(pool.clone());
        repo.import(&bundle, false).await.expect("first import");
        let mut counts = Vec::new();
        for (table, _) in EXPECTED_ROWS {
            counts.push(crate::pgtest::rows(&pool, table).await);
        }

        let second = repo.import(&bundle, false).await.expect("second import");
        for (table, want) in EXPECTED_ROWS {
            let r = second
                .tables
                .iter()
                .find(|t| t.table == table)
                .unwrap_or_else(|| panic!("{table} missing from the report"));
            assert_eq!(r.created, 0, "{table} created a row on the second import");
            assert_eq!(i64::from(r.updated), want, "{table} updated count");
        }
        for (i, (table, _)) in EXPECTED_ROWS.into_iter().enumerate() {
            assert_eq!(
                crate::pgtest::rows(&pool, table).await,
                counts[i],
                "{table} grew on the second import"
            );
        }
    }

    /// An import writes nothing into the fifteen tables the format deliberately leaves out.
    ///
    /// An import is a write path reachable by anyone who may upload a document, so this list is the
    /// security design of the feature rather than a completeness question: `users`, `api_tokens`
    /// and `oidc_providers` are how an import would otherwise become the shortest route to granting
    /// yourself a role.
    #[sqlx::test(migrator = "crate::repo::MIGRATIONS")]
    #[ignore = "needs DATABASE_URL"]
    async fn the_tables_a_bundle_does_not_carry_are_untouched_by_an_import(pool: sqlx::PgPool) {
        let mut before = Vec::new();
        for table in NEVER_CARRIED {
            before.push(crate::pgtest::rows(&pool, table).await);
        }
        ConfigBundleRepo::new(pool.clone())
            .import(&testkit::full_bundle(), false)
            .await
            .expect("import");
        for (i, table) in NEVER_CARRIED.into_iter().enumerate() {
            assert_eq!(
                crate::pgtest::rows(&pool, table).await,
                before[i],
                "the import wrote to {table}"
            );
        }
    }

    /// Export reads back every row the import wrote.
    ///
    /// Containment rather than equality: a deployment seeds built-ins of its own, and the exporter
    /// filters those out, so the two documents are not the same length. What must hold is that no
    /// id the importer accepted is missing from what the exporter can see — which is the property a
    /// second deployment depends on when the bundle is carried onward.
    #[sqlx::test(migrator = "crate::repo::MIGRATIONS")]
    #[ignore = "needs DATABASE_URL"]
    async fn the_exporter_sees_every_row_the_importer_wrote(pool: sqlx::PgPool) {
        let sent = testkit::full_bundle();
        let repo = ConfigBundleRepo::new(pool.clone());
        repo.import(&sent, false).await.expect("import");
        let back = repo.export().await.expect("export");

        for p in &sent.profiles {
            assert!(
                back.profiles.iter().any(|q| q.id == p.id),
                "profile {}",
                p.id
            );
        }
        for g in &sent.node_groups {
            assert!(
                back.node_groups.iter().any(|h| h.id == g.id),
                "group {}",
                g.id
            );
        }
        for n in &sent.nodes {
            assert!(back.nodes.iter().any(|m| m.id == n.id), "node {}", n.id);
        }
        for t in &sent.thresholds {
            assert!(
                back.thresholds.iter().any(|u| u.id == t.id),
                "threshold {}",
                t.id
            );
        }
        assert!(back
            .url_checks
            .iter()
            .any(|u| u.node_id == sent.url_checks[0].node_id));
        assert!(back
            .dns_checks
            .iter()
            .any(|d| d.node_id == sent.dns_checks[0].node_id));
        assert!(back
            .event_rules
            .iter()
            .any(|r| r.id == sent.event_rules[0].id));
        assert!(back
            .report_schedules
            .iter()
            .any(|s| s.id == sent.report_schedules[0].id));
        assert!(back
            .analysis_schedules
            .iter()
            .any(|s| s.id == sent.analysis_schedules[0].id));
        assert_eq!(
            back.app_settings.map(|a| a.default_poll_interval_secs),
            Some(120)
        );
    }
}
