// SPDX-License-Identifier: AGPL-3.0-only
//! Storage and materialization for the WebUI's TLS certificate (ADR-044).
//!
//! [`crate::server_cert`] decides whether a certificate is serviceable; this module decides where it
//! lives and how nginx gets to see it. The split is what lets every rule about *acceptance* be
//! tested without a database.
//!
//! ## The row is the record; the file is a cache
//!
//! nginx reads a file, so a file has to exist — but making that file authoritative would put "import
//! a certificate" on the host's shell instead of in the product, and would be the only secret in
//! this system living outside the envelope. So the certificate of record is one PostgreSQL row, and
//! `server.pem` on the shared volume is written from it. Deleting the volume is safe.
//!
//! Materialization happens **before `serve()` binds** (`main.rs`), which is what makes the compose
//! files' `depends_on: core: {condition: service_healthy}` a real guarantee rather than a race that
//! usually goes the right way.
//!
//! ## The rule that protects an operator's certificate
//!
//! A self-signed certificate may be replaced silently — it is a bootstrap, and regenerating one
//! costs nothing. An **imported** one may never be. The case that makes this matter is an
//! unreadable key: the dev compose file mounts no KEK, so its key is regenerated on every restart
//! and a sealed private key stops opening. Treating that as "generate a new one" would replace an
//! operator's certificate because of a key rotation, which is exactly the silent loss ADR-017
//! forbids. Instead core leaves the materialized file alone, logs, and says so in the UI.
//!
//! [`TlsCertSource::Unknown`] — a token written by a newer core — is treated as *not* self-signed,
//! so the conservative branch is the one an unrecognised value falls into rather than the risky one.

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::{PgPool, Row};
use uuid::Uuid;
use yagra_secrets::{EnvelopeCipher, SealedSecret};

use crate::secrets::Kek;
use crate::server_cert::{self, ServerCert, RENEW_WITHIN_DAYS};
use crate::stored_enum::token_enum;

/// The file both nginx directives point at: chain and key in one place, so the writer's job is a
/// single rename and there is no window where the two disagree.
const BUNDLE_FILE: &str = "server.pem";

/// Where a certificate came from, and therefore whether core may replace it on its own.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum TlsCertSource {
    /// Generated by Yagra. Renewed automatically before it expires.
    SelfSigned,
    /// Imported by an operator. Never replaced except by another import.
    Imported,
    /// Written by a newer version of Yagra than the one reading it.
    // Grouped with `Imported` by `may_regenerate` — an unrecognised value has to land on the side
    // that destroys nothing. Kept as a `//` note: the reason is ours, the description above is the
    // client's, and `///` here is published verbatim to every API consumer.
    Unknown,
}

token_enum!(
    TlsCertSource,
    Unknown,
    "web_tls_config.source",
    [SelfSigned => "self_signed", Imported => "imported", Unknown => "unknown"]
);

impl TlsCertSource {
    /// Whether core may replace this certificate without an operator asking.
    ///
    /// Written as an allow-list of one rather than `!= Imported`, so a variant added later is
    /// non-regenerable until somebody decides otherwise.
    #[must_use]
    pub const fn may_regenerate(self) -> bool {
        matches!(self, Self::SelfSigned)
    }
}

/// The certificate the WebUI is serving. Never includes the private key.
//
// Every `///` below is published verbatim to API clients and into the generated site reference, so
// design rationale goes in `//` notes like this one.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct WebTlsView {
    pub source: TlsCertSource,
    /// The certificate chain in PEM, leaf first. Safe to distribute — this is what a client would
    /// add to a trust store or pass to `curl --cacert`.
    pub certificate: String,
    /// Distinguished name of the certificate's subject.
    pub subject: String,
    /// Distinguished name of the issuer. Equal to `subject` for a self-signed certificate.
    pub issuer: String,
    /// The hostnames and IP addresses this certificate is valid for.
    pub sans: Vec<String>,
    /// Start of the validity window, RFC 3339.
    pub not_before: String,
    /// End of the validity window, RFC 3339.
    pub not_after: String,
    /// Lowercase hex SHA-256 of the certificate, matching what a browser displays.
    pub fingerprint_sha256: String,
    /// Key type and size, for example `RSA-2048` or `ECDSA P-256`.
    pub key_algorithm: String,
    /// Days until expiry; negative once it has passed.
    pub expires_in_days: i64,
    /// When this certificate was imported or generated, RFC 3339.
    pub imported_at: String,
    /// The account that imported it, if it was imported by a signed-in user.
    pub imported_by: Option<String>,
    /// Whether the web server is currently serving this certificate. `false` means it is stored but
    /// has not reached the web container yet.
    // "Stored" and "being served" are different claims, and every other field here would look
    // correct while the answer to the second one was no.
    pub materialized: bool,
    /// Whether the private key can still be decrypted. `false` means the encryption key has changed
    /// or been lost: the certificate cannot be served or renewed until it is imported again.
    pub key_unreadable: bool,
}

/// The WebUI certificate's contribution to System Health.
#[derive(Debug, Clone, Copy)]
pub struct TlsHealth {
    /// `false` only when an operator has to act. See [`WebTlsRepo::health`].
    pub ok: bool,
    /// Days until expiry; negative once it has passed.
    pub days: i64,
    pub source: TlsCertSource,
}

/// A decrypted row, or the reason there is nothing usable.
enum Stored {
    /// No row: nothing has ever been generated or imported.
    Absent,
    /// Usable.
    Ready {
        source: TlsCertSource,
        cert: ServerCert,
    },
    /// The row exists and its metadata is readable, but the sealed key will not open.
    KeyUnreadable { source: TlsCertSource },
}

/// PostgreSQL-backed store plus the volume writer.
pub struct WebTlsRepo {
    pool: PgPool,
    cipher: EnvelopeCipher<Kek>,
    /// `YAGRA_TLS_DIR`. `None` on a deployment that terminates TLS elsewhere — then this module
    /// still keeps the row, and simply has nowhere to write it.
    dir: Option<PathBuf>,
}

impl WebTlsRepo {
    #[must_use]
    pub fn new(pool: PgPool, kek: Kek, dir: Option<PathBuf>) -> Self {
        Self {
            pool,
            cipher: EnvelopeCipher::new(kek),
            dir,
        }
    }

    // ── Reads ────────────────────────────────────────────────────────────────────────────────

    /// The row as the settings page shows it, or `None` before anything has been generated.
    pub async fn view(&self) -> anyhow::Result<Option<WebTlsView>> {
        let Some(row) = sqlx::query(VIEW_SQL).fetch_optional(&self.pool).await? else {
            return Ok(None);
        };
        let source = TlsCertSource::from_stored(&row.try_get::<String, _>("source")?);
        let certificate: String = row.try_get("certificate")?;
        let not_after: DateTime<Utc> = row.try_get("not_after")?;
        let not_before: DateTime<Utc> = row.try_get("not_before")?;
        let imported_at: DateTime<Utc> = row.try_get("imported_at")?;
        let sans: serde_json::Value = row.try_get("sans")?;
        let fingerprint: String = row.try_get("fingerprint_sha256")?;

        // Cheap and worth it: "the page says the new certificate is stored" and "nginx is serving
        // it" are different claims, and only the second one is what the operator asked for.
        let materialized = self.materialized_matches(&certificate);
        let key_unreadable = matches!(self.load().await, Ok(Stored::KeyUnreadable { .. }));

        Ok(Some(WebTlsView {
            source,
            certificate,
            subject: row.try_get("subject")?,
            issuer: row.try_get("issuer")?,
            sans: serde_json::from_value(sans).unwrap_or_default(),
            not_before: not_before.to_rfc3339(),
            not_after: not_after.to_rfc3339(),
            fingerprint_sha256: fingerprint,
            key_algorithm: row.try_get("key_algorithm")?,
            expires_in_days: (not_after - Utc::now()).num_days(),
            imported_at: imported_at.to_rfc3339(),
            imported_by: row.try_get("imported_by_username")?,
            materialized,
            key_unreadable,
        }))
    }

    /// A one-line verdict for System Health, and the gauge value behind it.
    ///
    /// Reads only the plaintext metadata columns — no decrypt, no file read — because this is on a
    /// page that gets polled, unlike [`Self::view`] which answers one operator's deliberate visit.
    ///
    /// `ok = false` is reserved for "somebody has to do something": expired, or an **imported**
    /// certificate inside the renewal window. A self-signed one near expiry is not a problem — it
    /// renews itself — and reporting it as degraded would teach operators that degraded means
    /// nothing. Returns `None` when there is no certificate at all, which callers report the way
    /// they report an unconfigured optional store.
    pub async fn health(&self) -> anyhow::Result<Option<TlsHealth>> {
        let Some(row) = sqlx::query(HEALTH_SQL).fetch_optional(&self.pool).await? else {
            return Ok(None);
        };
        let source = TlsCertSource::from_stored(&row.try_get::<String, _>("source")?);
        let not_after: DateTime<Utc> = row.try_get("not_after")?;
        let days = (not_after - Utc::now()).num_days();
        let ok = if days < 0 {
            false
        } else if source.may_regenerate() {
            true
        } else {
            days > RENEW_WITHIN_DAYS
        };
        Ok(Some(TlsHealth { ok, days, source }))
    }

    async fn load(&self) -> anyhow::Result<Stored> {
        let Some(row) = sqlx::query(LOAD_SQL).fetch_optional(&self.pool).await? else {
            return Ok(Stored::Absent);
        };
        let source = TlsCertSource::from_stored(&row.try_get::<String, _>("source")?);
        let certificate: String = row.try_get("certificate")?;

        let sealed = SealedSecret {
            key_id: u32::try_from(row.try_get::<i32, _>("key_id")?).unwrap_or(0),
            wrapped_dek: row.try_get("wrapped_dek")?,
            dek_nonce: row.try_get("dek_nonce")?,
            ciphertext: row.try_get("ciphertext")?,
            ct_nonce: row.try_get("ct_nonce")?,
        };
        let Ok(key_bytes) = self.cipher.open(&sealed) else {
            return Ok(Stored::KeyUnreadable { source });
        };
        let key_pem = String::from_utf8(key_bytes).unwrap_or_default();

        // Re-validated rather than reassembled from the columns. The metadata columns are derived
        // data, and trusting them here would mean a hand-edited row could put an expired or
        // mismatched pair in front of nginx without anything noticing.
        match server_cert::validate(&certificate, &key_pem) {
            Ok(cert) => Ok(Stored::Ready { source, cert }),
            Err(e) => {
                // Expiry is the expected way to land here, and it is not a reason to serve nothing:
                // an expired certificate still encrypts, and taking the UI down would remove the
                // page the operator needs in order to fix it.
                tracing::warn!(error = %e, "the stored TLS certificate no longer validates");
                Ok(Stored::KeyUnreadable { source })
            }
        }
    }

    // ── Writes ───────────────────────────────────────────────────────────────────────────────

    /// Import an operator-supplied pair. Validates before it commits, so a stored row is always one
    /// that was serviceable when written.
    ///
    /// # Errors
    /// [`CertError`] for anything the operator can fix; otherwise the database error.
    pub async fn import(
        &self,
        chain_pem: &str,
        key_pem: &str,
        by: Option<Uuid>,
    ) -> anyhow::Result<WebTlsView> {
        let cert = server_cert::validate(chain_pem, key_pem)?;
        self.store(&cert, TlsCertSource::Imported, by).await?;
        self.materialize(&cert);
        self.view()
            .await?
            .ok_or_else(|| anyhow::anyhow!("certificate stored but could not be read back"))
    }

    /// Replace the current certificate with a freshly generated self-signed one covering `names`.
    ///
    /// # Errors
    /// [`CertError`] if generation fails, otherwise the database error.
    pub async fn regenerate(
        &self,
        names: &[String],
        by: Option<Uuid>,
    ) -> anyhow::Result<WebTlsView> {
        let cert = server_cert::generate_self_signed(names, Utc::now())?;
        self.store(&cert, TlsCertSource::SelfSigned, by).await?;
        self.materialize(&cert);
        self.view()
            .await?
            .ok_or_else(|| anyhow::anyhow!("certificate stored but could not be read back"))
    }

    async fn store(
        &self,
        cert: &ServerCert,
        source: TlsCertSource,
        by: Option<Uuid>,
    ) -> anyhow::Result<()> {
        let sealed = self
            .cipher
            .seal(cert.key_pem.as_bytes())
            .map_err(|e| anyhow::anyhow!("seal the TLS private key: {e}"))?;
        sqlx::query(SAVE_SQL)
            .bind(source.as_str())
            .bind(&cert.chain_pem)
            .bind(i32::try_from(sealed.key_id).unwrap_or(0))
            .bind(&sealed.wrapped_dek)
            .bind(&sealed.dek_nonce)
            .bind(&sealed.ciphertext)
            .bind(&sealed.ct_nonce)
            .bind(&cert.meta.subject)
            .bind(&cert.meta.issuer)
            .bind(serde_json::to_value(&cert.meta.sans)?)
            .bind(cert.meta.not_before)
            .bind(cert.meta.not_after)
            .bind(&cert.meta.fingerprint_sha256)
            .bind(&cert.meta.key_algorithm)
            .bind(by)
            .execute(&self.pool)
            .await?;
        Ok(())
    }

    // ── Startup and renewal ──────────────────────────────────────────────────────────────────

    /// Make sure a certificate exists and the file nginx reads is current. Called before the API
    /// binds its listener.
    ///
    /// Never returns an error that should stop startup: a core that refuses to boot because it could
    /// not write a certificate takes the API down as well as the UI, and the web container already
    /// fails loudly and specifically on its own. Two clear signals beat one silent one.
    pub async fn ensure_ready(&self, names: &[String]) {
        self.publish_expiry_gauge().await;
        match self.load().await {
            Ok(Stored::Ready { source, cert }) => {
                if source.may_regenerate() && cert.expires_within(RENEW_WITHIN_DAYS, Utc::now()) {
                    tracing::info!(
                        not_after = %cert.meta.not_after,
                        "self-signed TLS certificate is near expiry — renewing"
                    );
                    // Renew with the names it already covers, not the defaults: an operator who
                    // regenerated it with their real hostname must not silently lose that at renewal.
                    let names = if cert.meta.sans.is_empty() {
                        names.to_vec()
                    } else {
                        cert.meta.sans.clone()
                    };
                    if let Err(e) = self.regenerate(&names, None).await {
                        tracing::error!(error = %e, "could not renew the self-signed TLS certificate");
                        self.materialize(&cert);
                    }
                } else {
                    self.materialize(&cert);
                }
            }
            Ok(Stored::Absent) => match self.adopt_or_generate(names).await {
                Ok(()) => {}
                Err(e) => {
                    tracing::error!(error = %e, "could not establish a WebUI TLS certificate")
                }
            },
            Ok(Stored::KeyUnreadable { source }) => {
                if source.may_regenerate() {
                    tracing::warn!(
                        "the stored self-signed TLS certificate is unusable (most likely the KEK \
                         changed) — generating a new one"
                    );
                    if let Err(e) = self.regenerate(names, None).await {
                        tracing::error!(error = %e, "could not regenerate the TLS certificate");
                    }
                } else {
                    // The load-bearing branch. Replacing it here would destroy an operator's
                    // certificate because a key rotation made it unreadable.
                    tracing::error!(
                        "the imported WebUI TLS certificate cannot be decrypted — the KEK has \
                         changed or been lost. Leaving the materialized certificate in place and \
                         NOT replacing it. Restore the KEK, or import the certificate again at \
                         Settings ▸ TLS."
                    );
                }
            }
            Err(e) => tracing::error!(error = %e, "could not read the WebUI TLS certificate"),
        }
    }

    /// Publish days-until-expiry so an operator's own Prometheus can alert on it.
    ///
    /// Self-observability rather than a Yagra alert: the alert engine is for monitored devices, and
    /// routing a fact about Yagra's own configuration through it would need a synthetic node. A
    /// gauge plus the System Health verdict says the same thing through mechanisms that already
    /// exist. Zero cardinality — one series, no labels.
    async fn publish_expiry_gauge(&self) {
        if let Ok(Some(h)) = self.health().await {
            #[allow(clippy::cast_precision_loss)] // days fits a f64 exactly at any plausible value
            metrics::gauge!("yagra_web_tls_expires_in_days").set(h.days as f64);
            if !h.ok {
                tracing::warn!(
                    days = h.days,
                    source = h.source.as_str(),
                    "the WebUI TLS certificate needs attention — import a replacement at \
                     Settings ▸ TLS"
                );
            }
        }
    }

    /// No row. Adopt whatever is already materialized if it is usable, otherwise generate.
    ///
    /// Adoption matters after a database restore onto a machine whose volume survived: regenerating
    /// would hand every operator a new fingerprint and a fresh browser warning for no reason. The
    /// source is inferred from the certificate rather than guessed — a self-issued leaf is one core
    /// could have produced, anything else came from a CA and is treated as imported.
    async fn adopt_or_generate(&self, names: &[String]) -> anyhow::Result<()> {
        if let Some(cert) = self.read_materialized() {
            let source = if cert.meta.subject == cert.meta.issuer {
                TlsCertSource::SelfSigned
            } else {
                TlsCertSource::Imported
            };
            tracing::info!(
                fingerprint = %cert.meta.fingerprint_sha256,
                source = source.as_str(),
                "adopting the TLS certificate already on the volume rather than replacing it"
            );
            self.store(&cert, source, None).await?;
            self.materialize(&cert);
            return Ok(());
        }
        tracing::info!("no WebUI TLS certificate yet — generating a self-signed one");
        let cert = server_cert::generate_self_signed(names, Utc::now())?;
        self.store(&cert, TlsCertSource::SelfSigned, None).await?;
        self.materialize(&cert);
        Ok(())
    }

    // ── The volume ───────────────────────────────────────────────────────────────────────────

    fn bundle_path(&self) -> Option<PathBuf> {
        self.dir.as_ref().map(|d| d.join(BUNDLE_FILE))
    }

    fn read_materialized(&self) -> Option<ServerCert> {
        let text = std::fs::read_to_string(self.bundle_path()?).ok()?;
        // The bundle holds both, so the chain is validated against the key sitting beside it.
        server_cert::validate(&text, &text).ok()
    }

    fn materialized_matches(&self, chain_pem: &str) -> bool {
        self.bundle_path()
            .and_then(|p| std::fs::read_to_string(p).ok())
            .is_some_and(|text| text.starts_with(chain_pem))
    }

    /// Write the bundle atomically. Logs on failure and does not propagate — see [`Self::ensure_ready`].
    fn materialize(&self, cert: &ServerCert) {
        let Some(dir) = self.dir.clone() else {
            return;
        };
        if let Err(e) = self.write_bundle(&dir, cert) {
            tracing::error!(
                dir = %dir.display(), error = %e,
                "could not write the WebUI TLS certificate; the web container will refuse to start \
                 rather than serve plaintext on its TLS port"
            );
        } else {
            tracing::info!(
                dir = %dir.display(),
                fingerprint = %cert.meta.fingerprint_sha256,
                not_after = %cert.meta.not_after,
                "materialized the WebUI TLS certificate"
            );
        }
    }

    fn write_bundle(&self, dir: &std::path::Path, cert: &ServerCert) -> std::io::Result<()> {
        use std::io::Write;

        std::fs::create_dir_all(dir)?;
        let tmp = dir.join("server.pem.tmp");
        let dst = dir.join(BUNDLE_FILE);

        // Create restrictively and *then* write, so the private key is never briefly readable by
        // anyone the final mode would exclude.
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create(true).truncate(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.mode(0o600);
        }
        let mut f = opts.open(&tmp)?;
        f.write_all(cert.bundle_pem().as_bytes())?;
        // Durable before the rename: a crash between the two would otherwise leave nginx pointed at
        // a file whose contents never reached the disk.
        f.sync_all()?;
        drop(f);

        // 0640, not 0600: nginx runs as a different uid and reads this as a group member. Set
        // explicitly rather than relying on the create mode, which umask can narrow.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o640))?;
        }

        std::fs::rename(&tmp, &dst)?;
        Ok(())
    }
}

/// The names a bootstrap certificate covers, from the environment.
///
/// `YAGRA_TLS_SELF_SIGNED_SANS` is a comma-separated list; without it, loopback plus the container's
/// hostname. Nothing inside the container can know the address an operator will actually type, which
/// is why Settings ▸ TLS can regenerate with names they supply.
#[must_use]
pub fn configured_names() -> Vec<String> {
    let configured: Vec<String> = std::env::var("YAGRA_TLS_SELF_SIGNED_SANS")
        .unwrap_or_default()
        .split(',')
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
        .collect();
    if !configured.is_empty() {
        return configured;
    }
    server_cert::default_self_signed_names(std::env::var("HOSTNAME").ok().as_deref())
}

/// Whether core's own plaintext API port is published beyond loopback.
///
/// Read from `YAGRA_API_BIND`, which is a *compose* variable — core itself binds whatever
/// `YAGRA_API_ADDR` says on the container's own network, and cannot observe the host-side
/// publication. So this reports the operator's stated intent rather than an observed fact, and the
/// UI phrases it that way.
///
/// It exists because Settings ▸ TLS has to be able to say the thing that is otherwise invisible:
/// terminating TLS at the edge only makes the edge the *only* way in once this port is closed. That
/// is the documented second step after importing a real certificate (ADR-044 decision 9), and an
/// operator who never hears about it has a hole nobody told them about.
#[must_use]
pub fn api_port_is_public() -> bool {
    let bind = std::env::var("YAGRA_API_BIND").unwrap_or_default();
    let bind = bind.trim();
    // Unset is the default, and the default is public.
    bind.is_empty() || !(bind.starts_with("127.") || bind == "::1" || bind == "localhost")
}

/// How often the renewal check runs. A certificate's remaining life is measured in months, so this
/// is about surviving a long-running process rather than about precision — a core that has been up
/// for a year still notices before the bootstrap certificate lapses.
pub const RENEWAL_CHECK_INTERVAL: std::time::Duration = std::time::Duration::from_secs(12 * 3600);

const VIEW_SQL: &str = "SELECT t.source, t.certificate, t.subject, t.issuer, t.sans, \
     t.not_before, t.not_after, t.fingerprint_sha256, t.key_algorithm, t.imported_at, \
     u.username AS imported_by_username \
     FROM web_tls_config t LEFT JOIN users u ON u.id = t.imported_by \
     WHERE t.id = 1";

/// Two plaintext columns, for the polled health check. Kept separate from [`VIEW_SQL`] so the page
/// that refreshes on a timer never pays for the join or the certificate body.
const HEALTH_SQL: &str = "SELECT source, not_after FROM web_tls_config WHERE id = 1";

/// Everything [`WebTlsRepo::load`] needs, including the seal.
///
/// Kept apart from [`VIEW_SQL`] on purpose: the view is what the API answers with, and the sealed
/// columns must not be reachable from it even by accident.
const LOAD_SQL: &str = "SELECT source, certificate, key_id, wrapped_dek, dek_nonce, ciphertext, \
     ct_nonce FROM web_tls_config WHERE id = 1";

/// The upsert. A named constant so its semantics are assertable without a database.
///
/// Every column is replaced, including the seal — unlike `ldap_config`, there is no keep-the-stored-
/// secret case here, because a certificate and its key are only ever written together. A partial
/// update would be a pair that does not match.
const SAVE_SQL: &str = "INSERT INTO web_tls_config \
     (id, source, certificate, key_id, wrapped_dek, dek_nonce, ciphertext, ct_nonce, \
      subject, issuer, sans, not_before, not_after, fingerprint_sha256, key_algorithm, \
      imported_at, imported_by) \
     VALUES (1,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14, now(), $15) \
     ON CONFLICT (id) DO UPDATE SET \
       source = EXCLUDED.source, certificate = EXCLUDED.certificate, \
       key_id = EXCLUDED.key_id, wrapped_dek = EXCLUDED.wrapped_dek, \
       dek_nonce = EXCLUDED.dek_nonce, ciphertext = EXCLUDED.ciphertext, \
       ct_nonce = EXCLUDED.ct_nonce, subject = EXCLUDED.subject, issuer = EXCLUDED.issuer, \
       sans = EXCLUDED.sans, not_before = EXCLUDED.not_before, not_after = EXCLUDED.not_after, \
       fingerprint_sha256 = EXCLUDED.fingerprint_sha256, key_algorithm = EXCLUDED.key_algorithm, \
       imported_at = now(), imported_by = EXCLUDED.imported_by";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_source_round_trips_through_its_token_and_through_serde() {
        // The column value and the JSON tag are produced by two different mechanisms — `as_str` and
        // `#[serde(rename_all)]` — and nothing else makes them agree. A disagreement means rows the
        // writer produces are rows the reader cannot parse (testing.md).
        for s in TlsCertSource::ALL.iter().copied() {
            assert_eq!(TlsCertSource::from_stored(s.as_str()), s);
            let json = serde_json::to_string(&s).unwrap();
            assert_eq!(json, format!("\"{}\"", s.as_str()));
            assert_eq!(
                serde_json::from_str::<TlsCertSource>(&json).unwrap(),
                s,
                "serde tag and stored token disagree for {s:?}"
            );
        }
    }

    #[test]
    fn an_unrecognised_token_lands_on_the_side_that_destroys_nothing() {
        // A newer core could write a source this build has never heard of. Whatever it is, core must
        // not decide it may replace it.
        let unknown = TlsCertSource::from_stored("acme");
        assert_eq!(unknown, TlsCertSource::Unknown);
        assert!(!unknown.may_regenerate());
        assert!(!TlsCertSource::Imported.may_regenerate());
        assert!(TlsCertSource::SelfSigned.may_regenerate());
    }

    #[test]
    fn the_view_query_cannot_return_the_private_key() {
        // The one thing this module must never do. An in-memory fake cannot catch a mistake in SQL
        // meaning, so the statement itself is the thing under test.
        for sealed in ["wrapped_dek", "dek_nonce", "ct_nonce", "key_id"] {
            assert!(
                !VIEW_SQL.contains(sealed),
                "VIEW_SQL selects `{sealed}` — the view is what the API answers with"
            );
        }
        assert!(
            !VIEW_SQL.contains("ciphertext"),
            "VIEW_SQL selects the ciphertext"
        );
        // …and the loader, which is allowed to, actually does — otherwise this pair of assertions
        // would still pass with the seal accidentally dropped from both.
        assert!(LOAD_SQL.contains("ciphertext"));
    }

    #[test]
    fn the_upsert_replaces_the_seal_rather_than_preserving_it() {
        // The opposite of `ldap_config`'s keep-the-password clause, and deliberately so: a
        // certificate and its key are only ever written together, so preserving one across an
        // update would leave a pair that does not match.
        assert!(SAVE_SQL.contains("ON CONFLICT (id) DO UPDATE"));
        for col in [
            "ciphertext = EXCLUDED.ciphertext",
            "wrapped_dek = EXCLUDED.wrapped_dek",
            "certificate = EXCLUDED.certificate",
        ] {
            assert!(SAVE_SQL.contains(col), "SAVE_SQL does not set `{col}`");
        }
        assert!(
            !SAVE_SQL.contains("CASE WHEN"),
            "SAVE_SQL grew a keep-the-stored-secret clause; a half-updated pair does not match"
        );
    }

    #[test]
    fn configured_names_prefer_the_explicit_list() {
        // Uses the real environment, so assert only on the shape that does not depend on it.
        let names = server_cert::default_self_signed_names(Some("box.example.net"));
        assert_eq!(names.first().map(String::as_str), Some("box.example.net"));
        assert!(names.iter().any(|n| n == "127.0.0.1"));
    }
}
