[package]
name = "hikyaku"
description = "Yagra-bus — task queue / message bus client for core⇄poller distribution."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
yagra-common = { path = "../yagra-common" }
thiserror = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
