-- 0099_bus_callout — the NATS account key core signs per-poller credentials with (ADR-065 Inc.7).
--
-- Additive only (ADR-017 expand-contract): one new table. An older core never reads it, so rolling
-- the binary back leaves the row in place; the bus keeps running because the file the *server*
-- reads (`callout.conf`) is written by the `bus-cert` one-shot from whichever image is deployed.
--
-- **No `schema_compat` floor, deliberately** — 0089's argument, unchanged: this adds a table and
-- narrows nothing, and every release from 0.2.2 on tolerates a database carrying migrations it does
-- not embed. The floor 0080 already recorded covers this one.
--
-- WHY THE KEY IS A ROW AND NOT A MOUNTED FILE
-- ADR-030 shipped this key as an operator-mounted seed file (`YAGRA_NATS_CALLOUT_SEED_FILE`) and
-- the feature has never once run in production, because the other half of the procedure — editing
-- `auth_callout` into `nats-server.conf` — cannot survive: `bus-cert-init` rewrites that file from
-- the image on every `up` (ADR-065 Inc.2 decision 3). So the documented path does not exist. Making
-- the key a row lets the product generate it, and lets the *same* one-shot that rewrites the server
-- configuration write the matching issuer into it, in one run from one image. Two halves that can
-- never disagree, instead of two halves an operator has to keep in step by hand.
--
-- The seed gets the same five sealed columns as `credentials`, `web_tls_config`, `bus_tls_config`,
-- `oidc_providers`, `ldap_config` and `llm_config` (ADR-018), with the same all-or-none CHECK so a
-- half-written seal can never be read back as a key.

CREATE TABLE IF NOT EXISTS bus_callout_config (
    id           SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),

    -- The account nkey SEED (`SA…`), sealed. This is the signing key for every per-poller JWT the
    -- callout mints: anyone holding it can mint a credential for any poller id, so it is the same
    -- class of secret as a device password and is sealed the same way.
    key_id       INTEGER  NOT NULL,
    wrapped_dek  BYTEA    NOT NULL,
    dek_nonce    BYTEA    NOT NULL,
    ciphertext   BYTEA    NOT NULL,
    ct_nonce     BYTEA    NOT NULL,

    -- The account PUBLIC key (`A…`), plaintext and deliberately so. It is not a secret — it is what
    -- NATS is told to trust, and it has to be written into `callout.conf` by a one-shot that has no
    -- reason to hold the KEK open longer than generating the row took. Storing it parsed follows
    -- `bus_tls_config`'s rule: nothing should have to decrypt to answer a question.
    issuer       TEXT     NOT NULL CHECK (length(trim(issuer)) > 0),

    -- The NATS account minted users are placed in. `$G` (the global account) unless a deployment
    -- has been given a different one; stored beside the key because the server's `auth_callout`
    -- block and core's signer must name the same account or every connection is refused.
    account      TEXT     NOT NULL DEFAULT '$G' CHECK (length(trim(account)) > 0),

    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CHECK (
        (key_id IS NULL AND wrapped_dek IS NULL AND dek_nonce IS NULL
             AND ciphertext IS NULL AND ct_nonce IS NULL)
        OR
        (key_id IS NOT NULL AND wrapped_dek IS NOT NULL AND dek_nonce IS NOT NULL
             AND ciphertext IS NOT NULL AND ct_nonce IS NOT NULL)
    )
);

COMMENT ON TABLE bus_callout_config IS
    'The NATS account key core signs per-poller Auth Callout credentials with (ADR-065 Inc.7). One '
    'row, generated by the bus-cert one-shot. callout.conf on the bus volume is a materialization '
    'of the issuer column, not the record.';
