// SPDX-License-Identifier: AGPL-3.0-only
//! MCP server (ADR-028, Phase 4 inward-facing AI tool surface).
//!
//! Exposes yagra-core's **read** seams to an MCP client (Claude Code/Desktop, an oncall operator's
//! AI client, or later the internal RCA agent of ADR-029) over **Streamable HTTP**. The transport is
//! an [`rmcp`] `StreamableHttpService` mounted into the existing axum `serve()` at `/mcp`, gated OFF
//! by default behind `YAGRA_ENABLE_MCP` ([`crate::config::Config::enable_mcp`]); when off the route is
//! not mounted (a request 404s), byte-identical to pre-MCP behavior (ADR-017, additive/N-1-safe).
//!
//! **Auth** is enforced in [`mcp_auth_mw`] before any tool runs: a valid bearer token (an API token,
//! [`crate::apitokens`], or a session token, [`crate::auth`]) with `View`. MCP is **always
//! authenticated even under `public_dashboard`** — an AI surface must never be anonymous. For
//! Increment 1 the gate is **fail-closed on scope**: only global-scope (`Scope::All`) principals may
//! use MCP, because tools do not yet filter output to a principal's visible groups (that is
//! Increment 2). All tools are **read-only**; there are no device-configuration tools (monitoring
//! lane, ADR-015/029), and no credential/secret is ever placed in a tool result (ADR-018; enforced
//! structurally in [`dto`] + its canary test).

mod dto;
mod tools;

use axum::extract::{Request, State};
use axum::http::StatusCode;
use axum::middleware::Next;
use axum::response::Response;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{Implementation, ProtocolVersion, ServerCapabilities, ServerInfo};
use rmcp::transport::streamable_http_server::{
    session::local::LocalSessionManager, StreamableHttpServerConfig, StreamableHttpService,
};
use rmcp::{tool_handler, ServerHandler};
use tokio_util::sync::CancellationToken;
use yagra_common::{Permission, Principal, Scope};

use crate::api::ApiState;

/// Instructions shown to the MCP client at `initialize` — sets expectations for the model.
const INSTRUCTIONS: &str = "Yagra network-monitoring, read-only. These tools query live node status, \
    alerts, metrics, topology, and traffic flows, and run on-demand Troubleshoot analyses \
    (anomaly/correlation/capacity/flap). There are no tools that change state or configure devices — \
    an analysis reads metric history and returns findings, it never notifies or edits a device. Start \
    with get_fleet_summary, then drill in with list_nodes / get_node_status / get_active_alerts / \
    query_metrics; use run_analysis for deeper diagnosis (poll a long run with get_analysis_findings). \
    Node ids are UUIDs; timestamps are RFC 3339 or Unix seconds as documented per tool.";

/// The MCP server handler: holds the shared read state and the macro-generated tool router. Cheap to
/// clone (the state is all `Arc`s); a fresh instance is created per session by the transport factory.
#[derive(Clone)]
pub struct YagraMcp {
    /// Shared read seams (inventory, metrics, alerts, flows, …). The tools in [`tools`] wrap these.
    state: ApiState,
    /// Tool dispatch table generated by `#[tool_router]` (see [`tools`]).
    tool_router: ToolRouter<YagraMcp>,
}

// `router = self.tool_router` dispatches through the router built once in `YagraMcp::new` (the
// default would rebuild it on every call).
#[tool_handler(router = self.tool_router)]
impl ServerHandler for YagraMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::LATEST)
            .with_instructions(INSTRUCTIONS.to_owned())
    }
}

/// Build the auth-gated MCP sub-router. `serve()` nests it at `/mcp`; every request first passes
/// [`mcp_auth_mw`], then the `StreamableHttpService` handles the MCP protocol (POST messages, GET SSE,
/// DELETE session end). The `cancel` token (a child of the server shutdown token) lets in-flight MCP
/// sessions drain on shutdown (ADR-017).
pub fn build_router(state: ApiState, cancel: CancellationToken) -> axum::Router {
    let factory_state = state.clone();
    // rmcp's StreamableHttpService ships DNS-rebinding protection that rejects any `Host` header not
    // in `allowed_hosts` (default `localhost`/`127.0.0.1`/`::1`) with 403. Yagra is reached at an
    // operator-chosen host (a LAN IP, a hostname behind a proxy), so the default would 403 every real
    // client. We rely on our own **mandatory Bearer auth** (`mcp_auth_mw`, which runs *before* this
    // service) as the actual gate — a DNS-rebinding attacker's browser can't supply a valid token, so
    // it's stopped at 401 regardless of Host. Default: disable the allowlist (accept any Host).
    // Operators who still want Host pinning set `YAGRA_MCP_ALLOWED_HOSTS` (comma-separated).
    let hosts = mcp_allowed_hosts();
    let config = StreamableHttpServerConfig::default().with_cancellation_token(cancel);
    let config = if hosts.is_empty() {
        config.disable_allowed_hosts()
    } else {
        config.with_allowed_hosts(hosts)
    };
    let service = StreamableHttpService::new(
        move || Ok(YagraMcp::new(factory_state.clone())),
        LocalSessionManager::default().into(),
        config,
    );
    axum::Router::new()
        .fallback_service(service)
        .layer(axum::middleware::from_fn_with_state(state, mcp_auth_mw))
}

/// Operator-configured `Host`-header allowlist for the MCP endpoint (`YAGRA_MCP_ALLOWED_HOSTS`,
/// comma-separated, e.g. `yagra.example.com,192.168.1.2:8080`). Empty/unset ⇒ the allowlist is
/// disabled and any Host is accepted (Bearer auth remains the gate — see `build_router`).
fn mcp_allowed_hosts() -> Vec<String> {
    std::env::var("YAGRA_MCP_ALLOWED_HOSTS")
        .ok()
        .map(|raw| {
            raw.split(',')
                .map(|h| h.trim().to_owned())
                .filter(|h| !h.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// Authenticate every `/mcp` request before the MCP protocol handler runs. A denial short-circuits
/// with the standard error envelope; a success passes through (the resolved principal is not yet
/// threaded into tool context — Increment 1 enforces authz entirely here, see the module docs).
async fn mcp_auth_mw(State(st): State<ApiState>, req: Request, next: Next) -> Response {
    match authenticate(&st, crate::api::bearer(req.headers())).await {
        Ok(_principal) => next.run(req).await,
        Err(resp) => {
            metrics::counter!("yagra_mcp_auth_failures_total").increment(1);
            resp
        }
    }
}

/// Resolve a bearer token to a [`Principal`] permitted to use MCP, or an error `Response`. Routes by
/// token shape: a `yat_` API token → [`crate::apitokens::ApiTokenStore::verify`]; otherwise a session
/// token → [`crate::auth::SessionStore::authorize`]. Requires `View` and (Increment 1) global scope.
async fn authenticate(st: &ApiState, token: Option<&str>) -> Result<Principal, Response> {
    let Some(token) = token else {
        return Err(unauthorized("a valid bearer token is required"));
    };
    let principal = if crate::apitokens::is_api_token_shape(token) {
        // API tokens are backed by PostgreSQL (live mode only).
        match st.admin.as_ref() {
            Some(admin) => admin.api_tokens.verify(token).await,
            None => None,
        }
    } else {
        st.sessions
            .authorize(Some(token), Permission::View)
            .ok()
            .map(|session| session.principal)
    };
    let Some(principal) = principal else {
        return Err(unauthorized("invalid or expired token"));
    };
    if !principal.can(Permission::View) {
        return Err(forbidden("this token lacks view permission"));
    }
    // Fail-closed for Increment 1: tools return unfiltered (global) data, so only a global-scope
    // principal may use MCP. Group-scoped visibility inside tools ships in Increment 2.
    if principal.scope != Scope::All {
        return Err(forbidden(
            "group-scoped tokens are not yet supported on /mcp — use a global-scope (All) token",
        ));
    }
    Ok(principal)
}

fn unauthorized(message: &str) -> Response {
    crate::api::error_response(StatusCode::UNAUTHORIZED, "unauthorized", message.to_owned())
}

fn forbidden(message: &str) -> Response {
    crate::api::error_response(StatusCode::FORBIDDEN, "forbidden", message.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::{LoginThrottle, SessionStore};
    use std::sync::Arc;
    use yagra_common::{Principal, Role, Scope};

    /// A minimal state whose only wired pieces are the session store (for token auth) and the flag.
    /// `admin` is `None`, so PAT auth is unavailable — session tokens are the auth path under test.
    fn state_with_sessions(sessions: Arc<SessionStore>) -> ApiState {
        use crate::alerts::AlertManager;
        use crate::sink::InMemorySink;
        use crate::store::MetricStore;
        let store: Arc<dyn MetricStore> = Arc::new(InMemorySink::default());
        ApiState {
            store,
            logs: None,
            flows: None,
            ipasn: crate::ipasn::empty_handle(),
            host_sample: Arc::new(std::sync::Mutex::new(None)),
            nodes: Arc::new(crate::repo::StaticNodeList::demo()),
            alerts: Arc::new(AlertManager::new()),
            admin: None,
            sessions,
            login_throttle: Arc::new(LoginThrottle::new()),
            history: None,
            ack: None,
            events: None,
            public_dashboard: false,
            is_leader: Arc::new(std::sync::atomic::AtomicBool::new(true)),
            oidc: None,
            oidc_flight: Arc::new(crate::oidc::OidcFlight::new()),
            enable_mcp: true,
        }
    }

    #[tokio::test]
    async fn missing_token_is_unauthorized() {
        let st = state_with_sessions(Arc::new(SessionStore::new()));
        let resp = authenticate(&st, None).await.unwrap_err();
        assert_eq!(resp.status(), StatusCode::UNAUTHORIZED);
    }

    #[tokio::test]
    async fn invalid_token_is_unauthorized() {
        let st = state_with_sessions(Arc::new(SessionStore::new()));
        let resp = authenticate(&st, Some("not-a-real-token"))
            .await
            .unwrap_err();
        assert_eq!(resp.status(), StatusCode::UNAUTHORIZED);
    }

    #[tokio::test]
    async fn global_scope_viewer_session_is_accepted() {
        let sessions = Arc::new(SessionStore::new());
        let token = sessions.issue(
            uuid::Uuid::new_v4(),
            Principal::new(Role::Viewer, Scope::All),
            "viewer1",
        );
        let st = state_with_sessions(sessions);
        let principal = authenticate(&st, Some(&token)).await.expect("accepted");
        assert_eq!(principal.role, Role::Viewer);
    }

    #[tokio::test]
    async fn group_scoped_token_is_forbidden_in_increment_1() {
        let sessions = Arc::new(SessionStore::new());
        let token = sessions.issue(
            uuid::Uuid::new_v4(),
            Principal::new(Role::Operator, Scope::groups(["tokyo"])),
            "op1",
        );
        let st = state_with_sessions(sessions);
        let resp = authenticate(&st, Some(&token)).await.unwrap_err();
        assert_eq!(resp.status(), StatusCode::FORBIDDEN);
    }
}
