[package]
name = "yagra-transport"
description = "Yagra-transport — transport abstraction over ICMP / SNMP / HTTP device access."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
yagra-common = { path = "../yagra-common" }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
surge-ping = { workspace = true }
csnmp = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
