// SPDX-License-Identifier: AGPL-3.0-only
//! What making a report is allowed to reach, expressed as three traits (ADR-112).
//!
//! Before this file [`super::ReportRunner`] held four PostgreSQL-backed concrete types, and that
//! is why **521 production lines shipped with no tests**: not because nobody wrote them, but
//! because no test could construct the value they are methods on. ADR-102 decision 5 measured
//! that and stopped rather than turn a file split into a rewrite; this is the rest of it.
//!
//! The traits are cut by **what the caller needs**, never per repository (ADR-092 decision 1) —
//! thirteen methods against four concrete types with a hundred-odd between them. The same shape
//! as `analysis/seams.rs` (ADR-098) and `scheduler/seams.rs` (ADR-111).
//!
//! 🎯 **[`AlertFacts`] spans two stores on purpose.** `render_alert_summary` needs the live alerts
//! *and* the history inside one section — "active now" beside "fires in the window" is the whole
//! point of that table. Splitting it in two would be cutting per repository, which is the thing
//! the rule above forbids.
//!
//! 🎯 **[`AlertFacts::recent_history`] takes only a limit.** The real method takes
//! `(limit, before, before_id)` for keyset paging, and the one caller here has always passed
//! `(1000, None, None)`. Paging is not something a report does.
//!
//! ⚠️ **[`FleetInventory::node_names`] keeps its scope argument.** The only caller passes
//! "unrestricted", and it carries three lines saying why: a report is an admin-defined, fleet-wide
//! artefact generated by a background task with no requesting principal (ADR-014 non-goal).
//! Baking that `None` into the implementation below would move the decision out of reach of a
//! test — the mistake ADR-111 avoided by cutting the credential seam at the *sealed* bytes rather
//! than at a resolved credential.
//!
//! ⚠️ What this does **not** buy: [`super::ReportsRepo`] is 479 lines of SQL, so a fake
//! [`RunStore`] proves the runner *calls* it and never that the statement is right. That is the
//! same limit `repo/` has, and it is not a shape problem.

use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use uuid::Uuid;
use yagra_alert::Alert;
use yagra_common::{Node, NodeId, NodeState};

use crate::alerts::AlertManager;
use crate::history::{AlertHistoryRow, AlertHistoryStore};
use crate::repo::{GroupFilter, NodeRepo};

use super::{ReportDefinition, ReportRun, ReportRunTrigger, ReportsRepo};

// ── The run's life ───────────────────────────────────────────────────────────────────────────

/// Where a run is kept while it is being made: read the definition, insert the row, tick progress,
/// finish or fail.
///
/// Six methods of [`ReportsRepo`]'s nineteen. The other thirteen are the API's CRUD and the
/// leader's sweeps, which reach the store directly now (ADR-112 decision 3) rather than through
/// the generator.
#[async_trait]
pub(super) trait RunStore: Send + Sync {
    async fn get_definition(&self, id: Uuid) -> anyhow::Result<Option<ReportDefinition>>;
    #[allow(clippy::too_many_arguments)]
    async fn insert_run(
        &self,
        definition_id: Option<Uuid>,
        name: &str,
        trigger: ReportRunTrigger,
        from_s: i64,
        to_s: i64,
        section_count: i32,
        spec_snapshot: &serde_json::Value,
        created_by: Option<&str>,
    ) -> anyhow::Result<ReportRun>;
    async fn get_run(&self, id: Uuid) -> anyhow::Result<Option<ReportRun>>;
    async fn set_run_progress(&self, id: Uuid, pct: i32) -> anyhow::Result<()>;
    async fn finish_run(
        &self,
        id: Uuid,
        result: &serde_json::Value,
        html: &str,
    ) -> anyhow::Result<()>;
    async fn fail_run(&self, id: Uuid, error: &str) -> anyhow::Result<()>;
}

/// The production store. A direct impl rather than a wrapper: every method is already the shape
/// the caller wants, so a wrapping struct would be six lines of forwarding and one more name.
#[async_trait]
impl RunStore for ReportsRepo {
    async fn get_definition(&self, id: Uuid) -> anyhow::Result<Option<ReportDefinition>> {
        ReportsRepo::get_definition(self, id).await
    }

    async fn insert_run(
        &self,
        definition_id: Option<Uuid>,
        name: &str,
        trigger: ReportRunTrigger,
        from_s: i64,
        to_s: i64,
        section_count: i32,
        spec_snapshot: &serde_json::Value,
        created_by: Option<&str>,
    ) -> anyhow::Result<ReportRun> {
        ReportsRepo::insert_run(
            self,
            definition_id,
            name,
            trigger,
            from_s,
            to_s,
            section_count,
            spec_snapshot,
            created_by,
        )
        .await
    }

    async fn get_run(&self, id: Uuid) -> anyhow::Result<Option<ReportRun>> {
        ReportsRepo::get_run(self, id).await
    }

    async fn set_run_progress(&self, id: Uuid, pct: i32) -> anyhow::Result<()> {
        ReportsRepo::set_run_progress(self, id, pct).await
    }

    async fn finish_run(
        &self,
        id: Uuid,
        result: &serde_json::Value,
        html: &str,
    ) -> anyhow::Result<()> {
        ReportsRepo::finish_run(self, id, result, html).await
    }

    async fn fail_run(&self, id: Uuid, error: &str) -> anyhow::Result<()> {
        ReportsRepo::fail_run(self, id, error).await
    }
}

// ── What a report knows about the fleet ──────────────────────────────────────────────────────

/// The inventory a section reads: who is monitored, what they are called, and how many were in
/// each state over the window.
///
/// ⚠️ `state_history` is what separates this from `analysis/seams.rs`'s same-named trait, which
/// needs `group_edges` and does not need snapshots. Two traits with one name and different
/// methods is the rule working, not a copy to fold: each is the set *its* callers need.
#[async_trait]
pub(super) trait FleetInventory: Send + Sync {
    async fn list_nodes(&self) -> anyhow::Result<Vec<Node>>;
    /// `groups` is the scope filter, kept in the signature on purpose — see the module doc.
    async fn node_names(
        &self,
        groups: GroupFilter<'_>,
        ids: &[Uuid],
    ) -> anyhow::Result<HashMap<Uuid, String>>;
    /// `(ts_unix, state, count)` over `[from_s, to_s]`, oldest first.
    async fn state_history(
        &self,
        from_s: i64,
        to_s: i64,
    ) -> anyhow::Result<Vec<(i64, String, i64)>>;
}

#[async_trait]
impl FleetInventory for NodeRepo {
    async fn list_nodes(&self) -> anyhow::Result<Vec<Node>> {
        NodeRepo::list_nodes(self).await
    }

    async fn node_names(
        &self,
        groups: GroupFilter<'_>,
        ids: &[Uuid],
    ) -> anyhow::Result<HashMap<Uuid, String>> {
        NodeRepo::node_names(self, groups, ids).await
    }

    async fn state_history(
        &self,
        from_s: i64,
        to_s: i64,
    ) -> anyhow::Result<Vec<(i64, String, i64)>> {
        NodeRepo::state_history(self, from_s, to_s).await
    }
}

// ── What a report knows about alerting ───────────────────────────────────────────────────────

/// What is alerting now, and what has alerted over the window.
///
/// The two synchronous methods are the engine's in-memory snapshots; the two async ones are
/// PostgreSQL. They are one trait because one section needs both halves at once.
#[async_trait]
pub(super) trait AlertFacts: Send + Sync {
    fn active_alerts(&self) -> Vec<Alert>;
    fn node_states(&self) -> HashMap<NodeId, NodeState>;
    async fn recent_history(&self, limit: i64) -> anyhow::Result<Vec<AlertHistoryRow>>;
    async fn top_nodes_by_fires(
        &self,
        since_ms: i64,
        limit: i64,
    ) -> anyhow::Result<Vec<(Uuid, i64)>>;
}

/// The live engine plus its history store. The one wrapper here, because this trait is the one
/// whose methods come from two different types.
pub(super) struct LiveAlerts {
    alerts: Arc<AlertManager>,
    history: Arc<AlertHistoryStore>,
}

impl LiveAlerts {
    pub(super) const fn new(alerts: Arc<AlertManager>, history: Arc<AlertHistoryStore>) -> Self {
        Self { alerts, history }
    }
}

#[async_trait]
impl AlertFacts for LiveAlerts {
    fn active_alerts(&self) -> Vec<Alert> {
        self.alerts.active_alerts()
    }

    fn node_states(&self) -> HashMap<NodeId, NodeState> {
        self.alerts.node_states()
    }

    async fn recent_history(&self, limit: i64) -> anyhow::Result<Vec<AlertHistoryRow>> {
        self.history.recent(limit, None, None).await
    }

    async fn top_nodes_by_fires(
        &self,
        since_ms: i64,
        limit: i64,
    ) -> anyhow::Result<Vec<(Uuid, i64)>> {
        self.history.top_nodes_by_fires(since_ms, limit).await
    }
}
